language: scala
scala:
  - 2.12.2
jdk:
  - oraclejdk8
script:
  - sbt clean jacoco
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

after_success:
  - sbt jacocoCoveralls